//! Feature-parity scoreboard against the Python extractor.
//!
//! `fixtures/lines.json` is generated by `fixtures/generate_fixtures.py` from the
//! deployed Python feature stack, so every expected value in it is ground truth
//! rather than a guess. This test reports, per feature, how many cases the Rust
//! port reproduces exactly — porting is done when every count is 40/40 and the
//! test flips from reporting to asserting.
//!
//! It deliberately does not fail while the port is incomplete: an unported
//! feature is a known gap, not a regression. `PARITY_STRICT=1` turns it into a
//! hard assertion for CI once the port lands.

use bib_line_model::features::{line_counts, FEATURE_NAMES};
use serde::Deserialize;
use std::collections::BTreeMap;

#[derive(Deserialize)]
struct Case {
    text: String,
    counts: Vec<i64>,
}

#[derive(Deserialize)]
struct Fixture {
    feature_names: Vec<String>,
    n_cases: usize,
    cases: Vec<Case>,
}

#[test]
fn count_features_match_python() {
    let raw = std::fs::read_to_string(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/fixtures/lines.json"
    ))
    .expect("fixtures/lines.json — regenerate with fixtures/generate_fixtures.py");
    let fixture: Fixture = serde_json::from_str(&raw).expect("fixture parses");

    assert_eq!(
        fixture.feature_names.len(),
        FEATURE_NAMES.len(),
        "fixture has {} features, port declares {} — the schemas have diverged",
        fixture.feature_names.len(),
        FEATURE_NAMES.len()
    );
    for (i, name) in fixture.feature_names.iter().enumerate() {
        assert_eq!(
            name, FEATURE_NAMES[i],
            "feature {i} is {name:?} in the fixture but {:?} in the port — order matters",
            FEATURE_NAMES[i]
        );
    }

    let mut exact: BTreeMap<&str, usize> = BTreeMap::new();
    let mut first_diff: BTreeMap<&str, String> = BTreeMap::new();
    for case in &fixture.cases {
        let got = line_counts(&case.text);
        for (i, name) in FEATURE_NAMES.iter().enumerate() {
            let want = case.counts[i];
            if got[i] as i64 == want {
                *exact.entry(*name).or_insert(0) += 1;
            } else if !first_diff.contains_key(*name) {
                let mut snippet: String = case.text.chars().take(60).collect();
                if case.text.chars().count() > 60 {
                    snippet.push('…');
                }
                first_diff.insert(
                    *name,
                    format!("want {want}, got {} on {snippet:?}", got[i]),
                );
            }
        }
    }

    let n = fixture.n_cases;
    let done: Vec<&&str> = FEATURE_NAMES
        .iter()
        .filter(|f| exact.get(**f).copied().unwrap_or(0) == n)
        .collect();
    eprintln!(
        "\nfeature parity: {}/{} features exact on all {} cases",
        done.len(),
        FEATURE_NAMES.len(),
        n
    );
    for name in FEATURE_NAMES.iter() {
        let hit = exact.get(*name).copied().unwrap_or(0);
        if hit != n {
            eprintln!(
                "  {name:<28} {hit:>3}/{n}   {}",
                first_diff.get(*name).map(String::as_str).unwrap_or("")
            );
        }
    }

    if std::env::var("PARITY_STRICT").is_ok() {
        assert_eq!(
            done.len(),
            FEATURE_NAMES.len(),
            "PARITY_STRICT: {} features still diverge from Python",
            FEATURE_NAMES.len() - done.len()
        );
    }
}
