#!/usr/bin/env python3
"""Coordinator step 00: pre-flight checks before spinning up workers.

Verifies all the pins in `manifests/run_<RUN_ID>/text_dedup_pin.json`:
- git HEAD + text_dedup.py file hash
- live latest.json points to the named published bundle
- gcloud auth + project + zone
- HF_TOKEN set
- GCS bucket exists
- bucket-write permission (write+delete a small probe file)

Writes manifests/run_<RUN_ID>/preflight_status.md with PASS/FAIL per check.
Returns 0 if all PASS; non-zero halts the run.
"""
from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

REPO = Path("/home/foivos/Projects/glossapi-tokenizer-extension")
SUB = REPO / "subprojects/03_apertus_extension_and_embedding_adaptation/03_2_apertus_c3_dedup_audit"
RUN_ID = (SUB / "manifests/CURRENT_RUN_ID").read_text().strip()
MANI = SUB / f"manifests/run_{RUN_ID}"
PIN = json.loads((MANI / "text_dedup_pin.json").read_text())
STATUS_PATH = MANI / "preflight_status.md"

results: list[tuple[str, str, str]] = []


def check(name: str, ok: bool, note: str = "") -> None:
    results.append((name, "PASS" if ok else "FAIL", note))


def sh(cmd: list[str], **kw) -> str:
    r = subprocess.run(cmd, capture_output=True, text=True, **kw)
    return (r.stdout + r.stderr).strip()


def main() -> int:
    # Git pin
    head = sh(["git", "-C", str(REPO), "rev-parse", "HEAD"])
    check("git_head_full", head == PIN["text_dedup_commit"], f"got {head}")
    fh = sh(["git", "-C", str(REPO), "hash-object",
             "glossapi_corpus_cli/text_dedup.py"])
    check("text_dedup_file_hash", fh == PIN["text_dedup_file_hash_git"], f"got {fh}")

    # Latest.json
    live_lj = Path("/home/foivos/data/glossapi_work/hf_release_publish/dedup_metadata/latest.json")
    if live_lj.exists():
        lj = json.loads(live_lj.read_text())
        check("latest_json_pointer",
              lj["latest_run_id"] == PIN["published_bundle_pin"]["run_id"],
              f"got {lj.get('latest_run_id')}")
    else:
        check("latest_json_pointer", False, "missing latest.json")

    # Published bundle manifest greek_diacritic_policy (sanity — should be strip)
    pub_mani = Path(PIN["published_bundle_pin"]["path"]) / "builder_metadata/manifest.json"
    if pub_mani.exists():
        pm = json.loads(pub_mani.read_text())
        check("published_bundle_policy",
              pm["greek_diacritic_policy"] == PIN["published_bundle_pin"]["greek_diacritic_policy"],
              f"got {pm.get('greek_diacritic_policy')}")
    else:
        check("published_bundle_policy", False, "missing")

    # gcloud auth
    account = sh(["gcloud", "config", "get-value", "account"])
    check("gcloud_account", "@eellak" in account, f"got {account}")
    project = sh(["gcloud", "config", "get-value", "project"])
    check("gcloud_project", project == "eellak-glossapi-20251008", f"got {project}")

    # HF token
    import os
    check("hf_token_set", bool(os.environ.get("HF_TOKEN")), "env HF_TOKEN")

    # Bucket exists + write probe
    bucket = PIN["bucket"]
    bucket_check = sh(["gcloud", "storage", "buckets", "describe", bucket, "--format=value(name)"])
    check("bucket_exists", bucket_check.split()[-1] == bucket.replace("gs://", ""),
          f"got {bucket_check[:80]}")

    # Quota — try to verify PREEMPTIBLE_CPUS quota covers 8 * 192 = 1536
    quota_raw = sh(["gcloud", "compute", "regions", "describe", "europe-west4",
                    "--format=value(quotas[].metric,quotas[].limit,quotas[].usage)"])
    # Coarse check — just ensure PREEMPTIBLE_CPUS appears with enough room.
    # 8 × 192 = 1536 vCPU needed.
    check("preemptible_cpus_estimate", "PREEMPTIBLE_CPUS" in quota_raw,
          "see manual review if FAIL — region describe parse hint only")

    # Write the status doc
    lines = [
        f"# Pre-flight status — {RUN_ID}",
        "",
        f"Generated by `00_pre_flight.py`. Bucket: `{bucket}`.",
        "",
        "| Check | Result | Note |",
        "|---|---|---|",
    ]
    fail_count = 0
    for name, st, note in results:
        if st == "FAIL":
            fail_count += 1
        lines.append(f"| `{name}` | **{st}** | {note} |")
    lines.append("")
    if fail_count:
        lines.append(f"**{fail_count} check(s) FAILED** — DO NOT spin up workers.")
        rc = 2
    else:
        lines.append("**All checks PASS.** Run is cleared for spin-up.")
        rc = 0
    STATUS_PATH.write_text("\n".join(lines) + "\n")
    print(f"[pre_flight] wrote {STATUS_PATH}")
    print(f"[pre_flight] {fail_count} FAIL(s); exit {rc}")
    return rc


if __name__ == "__main__":
    sys.exit(main())
